[package]
name = "mmp_prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "25.1.24"
tokio = { version = "1.43.0", features = ["full"] }
dsnet = { path = "../dsnet" }
rand = "0.9.0"
